### PR TITLE
Simplify reference to protractor's Locator

### PR DESCRIPTION
**Pull request by scriby**

### CODE REVIEW

**Review by shermaneric — DISMISSED** [review]

**Comment by shermaneric** [comment]
sorry maybe too soon, i just noticed the CircleCI issue...

**Comment by scriby** [comment]
Hmm, it builds ok locally. I'll dig into it.

**Comment by scriby** [comment]
I think it's b/c the build server is running with an older protractor dependency. I tried updating it in package.json to see if that'll cause it to grab the latest.

**Review by shermaneric — APPROVED** [review]
looks good now!

**Comment by shermaneric** [comment]
Merging this PR then i'll increment the version and publish.  sorry for delay!

**Pull request merged**
