### PR TITLE
Increases protractor-sync version to 6.0.0.  

### PR DESCRIPTION
**Pull request by shermaneric**
Lists protractor 5.3 and above as the minimum version in the README and as a devDependency/peerDependency

### CODE REVIEW

**Comment by scriby** [comment]
LGTM

**Review by mindywhitsitt — APPROVED** [review]

**Review by richmischler — APPROVED** [review]

**Comment by shermaneric** [comment]
I'll ensure that the other PRs in play right now get merged in first before merging this PR in.

**Comment by scriby** [comment]
I'd appreciate it if you could let me know when 6.0.0 is up on npm. Thanks!

**Comment by shermaneric** [comment]
sorry.  6.0.0 is now updated here at https://www.npmjs.com/package/protractor-sync !

FYI.  I'm moving on June 1 from Blackboard (but will still hopefully be actively leveraging protractor-sync as a customer).  I've included some admin types from Blackboard into this repo with publish instructions going forward...

**Comment by scriby** [comment]
Thanks!

I really appreciate all the time, energy, and attention you've given to this project. It's been a joy to work with you and I wish you the best in your next endeavor!

**Comment by shermaneric** [comment]
So good news!  We got permission to add you @scriby and @steeltomato (Ken) back to this repo should you guys be interested in it as well as allowing me stay on.  I just sent the invites.  Hope this helps!

**Pull request merged**
