### PR TITLE
Add circleci spec

### PR DESCRIPTION
**Pull request by sharp-bits**
Enable CircleCI integration

### CODE REVIEW

**Comment by steeltomato** [comment]
I'm just playing with this for the moment. Not really ready for review.

**Comment by shermaneric** [comment]
Curious why we're using CircleCI and not Jenkins? (i'm cool either way)  Is CircleCI the defacto for open source projects?

**Comment by sharp-bits** [comment]
This is ready to go now. It just enables CircleCI to run `npm test` on each commit. No publish is needed for this PR. Next step will be to use CircleCI to autopublish whenever new commits are added to the develop branch.

**Comment by sharp-bits** [comment]
Jenkins is an on-premise, behind-the-firewall solution for CI. We can't use easily use it for this project. Our choices are TravisCI or CircleCI, both are cloud solutions and are free for open source projects. CircleCI seemed like it would be the easiest to get going for this project because it's based on docker image composition and the config is simple. This proved to be a decent assumption.

**Comment by mindywhitsitt** [comment]
Can we make it so that a PR cannot be merged if the ci build doesn't pass? Or do we just rely on the maintainers (us) to do the right thing and not merge a PR unless the build passes?

**Review by casteaux — APPROVED** [review]

**Review by mindywhitsitt — APPROVED** [review]

**Comment by casteaux** [comment]
@mindywhitsitt looks like we can add status checks... went ahead and gave it a shot

**Comment by shermaneric** [comment]
Nice job guys!  Ken, thanks for the detailed explanation on CircleCI usage.  Do we all have some degree of access on CircleCI?

**Pull request merged**
