### PR TITLE
upped protractor-sync package.json to 5.1.3

### PR DESCRIPTION
**Pull request by shermaneric**

### CODE REVIEW

**Comment by shermaneric** [comment]
@steeltomato - Should we still do the updating of package.json after a previous pull request/merge to develop [like in this PR](https://github.com/blackboard/protractor-sync/pull/8)
Totally fine if so.  One thought though is to stay in line with protractor version of 5.1.2.

Thanks!

**Comment by mindywhitsitt** [comment]
Ken and I talked about this and we think we should match Protractor's major version (5) while using our own minor and patch version numbers. So I guess we kinda did it wrong by jumping to 5.1.2, but whatever. :)

**Review by mindywhitsitt — APPROVED** [review]

**Comment by scriby** [comment]
Yeah I was thinking the same thing.

I looked into using the "-versions" like "5.1.2-a" or something like that. The problem is those are treated by npm as "pre-release" versions and won't be automatically selected (although it does work ok for explicit refs...). And there doesn't seem to be support for "5.1.2.1" or something like that.

So yeah, it would have been better to just match the major version. Assuming you guys have the time to do it, it's probably worthwhile to pull the existing release from npm and correct it.

**Comment by shermaneric** [comment]
Good call @scriby .  
We decided to correct the versioning to start at 5.0.0 and use semantic versioning going forward.
All should be updated now
Thanks again!

**Pull request merged**
