### PR TITLE
Re-select stale elements selected by querySelector and querySelectorAll.

### PR DESCRIPTION
**Pull request by scriby**

### CODE REVIEW

**Review by mindywhitsitt — DISMISSED** [review]

**Comment by shermaneric** [comment]
Thanks for this fix, looks really good!
minor: I'm not sure if this is down the wrong path, but I made a branch [here](https://github.com/blackboard/protractor-sync/compare/feature/sherman-query-selector-stale?expand=1). 

The only thought I had was in the newly added test `re-selects a stale element selected by querySelectorAll`, we could have multiple items returned  from `querySelectorAll`.  

1.  `appendStaleTestArea` looks like this with multiple **inner-stale-3** classes:
```
function appendStaleTestArea(extraClass = '') {
      appendTestArea({
        innerHtml: '<div class="stale-test ' + extraClass + '">' +
                   '  <div class="inner-stale ' + extraClass + '">' +
                   '    <div class="inner-stale-2 ' + extraClass +  '">test</div>' +
                   '    <div class="inner-stale-3 ' + extraClass +  '">' +
                   '    <div class="inner-stale-3 ' + extraClass +  '">' +
                   '  </div>' +
                   '  </div>' +
                   '  </div>' +
                   '</div>' +
                   '<div class="stale-test-2 ' + extraClass + '">test</div>' +
                   '<div class="stale-test-3 ' + extraClass + '" style="display:none">test</div>' +
                   '<div class="stale-test-3 ' + extraClass + '">test</div>'
      });
    }
```

2.  We would iterate through the inner3 array ensuring **each** of them contained the `extraClass` like so.
```
 it('re-selects a stale element selected by querySelectorAll', createTest(() => {
      const el = elementSync.findVisible('.inner-stale');
      const inner3 = el.querySelectorAll('.inner-stale-3');

      browserSync.executeScript(() => {
        const stale = document.querySelector('.stale-test');
        stale.parentNode.removeChild(stale);
      });

      appendStaleTestArea('second');

      inner3.forEach((element) => {
          expect(element.hasClass('second')).toEqual(true);
        });

    }));
```

Sorry again if overkill or way off base :).  I'm cool also merging as is.

Thanks!

**Comment by scriby** [comment]
I was just being lazy, of course your test is better :) Feel free to replace the one I added with it. Thanks!

**Comment by shermaneric** [comment]
I just can't picture you as lazy @scriby :)

**Comment by scriby** [comment]
Let's go with busy then :)

**Review by mindywhitsitt — APPROVED** [review]

**Pull request merged**
