### PR TITLE
Fix build breakage from dependency updates.

### LINKED ISSUE #77: Issues building
The latest develop seems to fail with

```
$ grunt build
Running "clean:build" (clean) task
>> 1 path cleaned.

Running "ts:build" (ts) task
Compiling...
Using the custom compiler : node_modules/typescript/bin/tsc
node_modules/@types/selenium-webdriver/remote.d.ts(139,29): error TS2304: Cannot find name 'Map'.
app/browser-sync.ts(146,10): error TS2346: Supplied parameters do not match any signature of call target.

>> 2 non-emit-preventing type warnings
>> Error: tsc return code: 2
Warning: Task "ts:build" failed. Use --force to continue.

Aborted due to warnings.
```

I'm using Node 8.6.0 - not quite sure how to fix that one.

### PR DESCRIPTION
**Pull request by scriby**
Fixes #77

### CODE REVIEW

**Review by ftclausen — DISMISSED** [review]

**Comment by ftclausen** [comment]
The failed test seems to be something quite trivial:

```
      ✗ resizes the window
        - Expected 582 to equal 550.`
```

**Comment by scriby** [comment]
Yeah not quite sure what’s going on here since the test passes locally... I don’t have much insight into how the circle ci tests are setup...

**Comment by scriby** [comment]
Got the build fixed, feel free to merge this if you still approve of the changes. Thanks!

**Review by ftclausen — APPROVED** [review]
Looks good to me!

**Pull request merged**
